CREATE DATABASE IF NOT EXISTS auth_service;
CREATE DATABASE IF NOT EXISTS vendor_service;
CREATE DATABASE IF NOT EXISTS item_service;
CREATE DATABASE IF NOT EXISTS project_service;
CREATE DATABASE IF NOT EXISTS boq_service;
